# Generated by Django 4.1.7 on 2023-03-08 17:49

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='textModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='textImages')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('category', models.ManyToManyField(related_name='text', to='blog.categorymodel')),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'Texts',
                'db_table': 'text',
            },
        ),
    ]
