# Generated by Django 4.1.7 on 2023-03-08 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='createdAtTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmodel',
            name='updatedAtTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
