from .contact import contactFormView
from .home import home
from .category import categoryListView
from .mytext import mytext
from .detail import detailView
from .addText import addTextCreateView
from .updateText import updateTextUpdateView
from .deleteText import deleteTextDeleteView
from .deleteComment import deleteComment